backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: editorial_workflow

site_url: "/"
logo_url: "/assets/images/logo.png"

# Mobile-friendly admin settings
display_url: "/"
site_domain: "/"

# Mobile-optimized interface
locale: "ar"

# Mobile-friendly collection settings
collections:
  - name: "site"
    label: "إعدادات الموقع"
    files:
      - label: "المحتوى العام"
        name: "content"
        file: "content.json"
        editor:
          preview: false
        fields:
          - { label: "عنوان الموقع", name: "site.title", widget: "string" }
          - { label: "وصف قصير", name: "site.tagline", widget: "string", required: false }
          - { label: "الشعار", name: "site.logo", widget: "image", required: false }
          - label: "الواجهة"
            name: "hero"
            widget: "object"
            fields:
              - { label: "عنوان", name: "title", widget: "string" }
              - { label: "وصف", name: "subtitle", widget: "string", required: false }
              - { label: "صورة", name: "image", widget: "image", required: false }
          - label: "من نحن"
            name: "about"
            widget: "object"
            fields:
              - { label: "نص", name: "text", widget: "text" }
              - { label: "نقاط", name: "bullets", widget: "list", field: { label: "عنصر", name: "item", widget: "string" } }
              - { label: "لماذا نحن", name: "whyUs", widget: "list", field: { label: "ميزة", name: "adv", widget: "string" } }
          - label: "الخدمات"
            name: "services"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "الوصف", name: "description", widget: "text" }
          - label: "المشاريع"
            name: "projects"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "الصورة", name: "image", widget: "image" }
              - { label: "الوصف", name: "caption", widget: "string", required: false }
          - label: "التواصل"
            name: "contact"
            widget: "object"
            fields:
              - { label: "نص", name: "blurb", widget: "text" }
              - label: "تفاصيل"
                name: "details"
                widget: "object"
                fields:
                  - { label: "الهاتف", name: "الهاتف", widget: "string", required: false }
                  - { label: "البريد", name: "البريد", widget: "string", required: false }
                  - { label: "العنوان", name: "العنوان", widget: "string", required: false }
              - { label: "واتساب (أرقام فقط)", name: "whatsapp", widget: "string", required: false }
              - { label: "رقم الاتصال", name: "phone", widget: "string", required: false }
          - label: "التذييل"
            name: "footer"
            widget: "object"
            fields:
              - { label: "العنوان", name: "address", widget: "string" }

# Mobile-optimized media handling
media_library:
  name: netlify
  config:
    use_transforms: true
    responsive: true
    breakpoints: [400, 600, 800, 1200, 1600]

# Mobile-friendly editor settings
editor:
  preview: false
  frame: false

# Mobile-optimized widgets
widgets:
  - name: string
    config:
      size: 20
  - name: text
    config:
      size: 10
  - name: image
    config:
      default: false
      allow_multiple: false
      choose_url: false
      media_library:
        config:
          multiple: false

